# docker-compose.yml
version: '3.5'
services:
  # MySQL
  database:
    container_name: "db"
    build: ./be/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: merv
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3306"
    volumes:
      - ./be/mysql/initdb.d/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./be/mysql/conf.d:/etc/mysql/conf.db
      - ./be/log/mysql:/var/log/mysql
    networks:
      - local-net
  
 
  backend:
    links:
      - database
    depends_on:
      - database
    container_name: backend
    build: ./be/
    ports:
      - "8000:8000"
    volumes:
      - ./be:/usr/src/server
    networks:
      - local-net

  frontend:
    links:
      - backend
    depends_on:
      - backend
    container_name: frontend
    build: ./fe/auth/
    ports:
      - 3000:80
    stdin_open: true
    tty: true 
    networks:
      - local-net   



networks:
  local-net:
    driver: bridge

